### ISSUE TITLE
Batch Effect Corrections

### ISSUE THREAD

**Issue by baracus37** [broadinstitute/single_cell_analysis#1]
Dear Timothy,

I came across your workshop material, trying to find a way to correct for batch effects in scRNA-Seq data with Seurat. First of all: thanks for sharing!
But I do have some issues understanding how your batch correction approach works. If I get it right, you basically are extracting information about batch from the @data.info slot, binning batches 1 to 4 into one batch and 5 to 6 into the second batch, adding this to the Seurat object and then regressing for it. But how can the computer regress out batch effects without knowing what genes or other confounders are driving a potential batch effect? Could you elaborate on how this is achieved?

Adding to my confusion, when you are showing the TSNE Plot (https://rstudio-pubs-static.s3.amazonaws.com/245975_cd7f2637adea45db83873c5c1f421e07.html#/68), there is one cluster present that solely consists of cells originating from bipolar1-4 (i.e. batch1) and a second one right underneath that is solely made up of cells from bipolar 5 and 6 (i.e. batch2). Isn't this the kind of batch effect that was supposed to be removed?

Best,

Tobias

**Comment by TimothyTickle** [comment]
Hello Tobias,

The workshop is for introductory concepts and beginners use of different tools, this part of the workshop was showing that it is possible to perform batch effect correction in Seurat and how one would do that. Although Seurat is an amazing tool, it is true that, in this case, the correction could be better but that requires tools outside the scope of the beginner and this workshop. I would encourage you to look at the more advanced version of this analysis where ComBat is used to account for technical batches.

https://github.com/broadinstitute/BipolarCell2016/blob/master/BCanalysis.pdf

Cordially,

Tim
